<?php
// admin/cron/morning_alert.php

// 1. การตั้งค่าเบื้องต้น
date_default_timezone_set('Asia/Bangkok');
require_once __DIR__ . '/../../includes/db.php';
require_once __DIR__ . '/telegram_helper.php';

$report_date = date('d/m/Y');
$report_time = date('H:i');

// 2. นิยามสถานะ (Status Definitions)
$status_def = [
    'QS'  => ['label' => 'รอตรวจสอบราคา',      'icon' => '🔸'],
    'WC'  => ['label' => 'รออนุมัติ/มัดจำ',      'icon' => '🔸'],
    'OK'  => ['label' => 'กำลังดำเนินการซ่อม',    'icon' => '🔹'],
    'RW'  => ['label' => 'งานแก้ไข/เคลม',       'icon' => '🔄'],
    'WP'  => ['label' => 'รออะไหล่',           'icon' => '📦'],
    'FN'  => ['label' => 'ซ่อมเสร็จ (รอรับ)',     'icon' => '✅'], 
    'NCS' => ['label' => 'ติดต่อไม่ได้ (เสนอราคา)', 'icon' => '📴'],
    'NCF' => ['label' => 'ติดต่อไม่ได้ (แจ้งรับ)',   'icon' => '📴'],
    'XX'  => ['label' => 'ยกเลิก (รอรับคืน)',    'icon' => '❌'],
];

// ลำดับการแสดงผลในรายงาน
$order_show = ['QS', 'NCS', 'WC', 'OK', 'WP', 'RW', 'FN', 'NCF', 'XX'];

// 3. ดึงข้อมูลงาน (Query)
try {
    // ดึงเฉพาะงานที่ยังอยู่ในร้าน (ตัด DV=ส่งมอบ, RT=คืนเครื่อง ออก)
    $sql = "SELECT ticket_number, customer_name, device_type, device_model, problem_details, status, appointment_date 
            FROM tracking 
            WHERE status NOT IN ('DV', 'RT') 
            ORDER BY created_at ASC";
    $stmt = $pdo->query($sql);
    $all_jobs = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    // กรณี Database มีปัญหา ให้หยุดทำงานเงียบๆ หรือ Log ไว้
    error_log("Morning Alert DB Error: " . $e->getMessage());
    exit;
}

// 4. จัดกลุ่มงานตามสถานะ
$grouped = [];
foreach ($all_jobs as $job) {
    $st = $job['status'];
    if (!isset($grouped[$st])) $grouped[$st] = [];
    $grouped[$st][] = $job;
}

// 5. สร้างส่วนหัวรายงาน (Header)
$msg = "🔔 <b>DAILY JOB STATUS (รายงานเช้า)</b>\n";
$msg .= "📅 $report_date | ⏰ $report_time น.\n";
$msg .= "📊 งานคงค้างหน้าร้าน: <b>" . count($all_jobs) . "</b> รายการ\n";
$msg .= "〰〰〰〰〰〰〰〰〰〰\n"; 

// 6. วนลูปสร้างเนื้อหารายงาน
foreach ($order_show as $st) {
    if (isset($grouped[$st]) && count($grouped[$st]) > 0) {
        $list = $grouped[$st];
        $count = count($list);
        $info = $status_def[$st] ?? ['label' => $st, 'icon' => '▪️'];
        
        // หัวข้อหมวดหมู่
        $msg .= "\n" . $info['icon'] . " <u><b>{$info['label']} ($count)</b></u>\n";
        
        foreach ($list as $job) {
            // -- จัดการข้อมูลให้สะอาด (Data Cleansing) --
            // 1. ล้าง HTML Tags ออกจากอาการเสีย
            $clean_problem = strip_tags($job['problem_details'] ?? '-');
            $clean_problem = str_replace(['&nbsp;', '&amp;'], [' ', '&'], $clean_problem);
            // 2. ตัดคำถ้าข้อยาวเกิน 40 ตัวอักษร
            $problem_short = mb_strimwidth(trim($clean_problem), 0, 40, '...');
            
            // 3. ตรวจสอบวันนัด (Appointment)
            $due_info = "";
            if (!empty($job['appointment_date'])) {
                $due_ts = strtotime($job['appointment_date']);
                $due_str = date('d/m', $due_ts);
                // เช็คว่าเกินกำหนดหรือยัง
                if (date('Y-m-d') > date('Y-m-d', $due_ts)) {
                    $due_info = "⚠️($due_str)"; // เกินกำหนด
                } else {
                    $due_info = "🗓$due_str";   // ยังไม่ถึง/ถึงวันนี้
                }
            }
            
            // 4. จัด format ประเภทเครื่อง
            $type = $job['device_type'] ? "[{$job['device_type']}]" : "";

            // -- เริ่มประกอบร่างข้อความ (Format 3 บรรทัด) --
            
            // บรรทัดที่ 1: รหัสงาน : [ประเภท] รุ่นเครื่อง
            $msg .= "  ▪️ <code>{$job['ticket_number']}</code> : {$type} <b>{$job['device_model']}</b>\n";
            
            // บรรทัดที่ 2: ชื่อลูกค้า + วันนัด
            $msg .= "      └ 👤 {$job['customer_name']} {$due_info}\n";
            
            // บรรทัดที่ 3: อาการเสีย
            $msg .= "      └ 🔧 {$problem_short}\n";
        }
        
        $msg .= "➖➖➖➖➖➖➖➖➖➖\n"; 
    }
}

// 7. ส่วนท้าย (Footer)
$msg .= "<i>🤖 Generated by Jarvis FixMac</i>";

// 8. ส่งเข้า Telegram
$res = sendTelegram($msg);

// 8.1 ส่งเข้า LINE คู่กัน (1:1 หา admin ที่ลงทะเบียนเท่านั้น) — ข้ามเงียบถ้ายังไม่ตั้ง token
require_once __DIR__ . '/../../includes/line_helper.php';
// LINE: การ์ด Flex สรุป + รายละเอียดเต็ม (เนื้อเดียวกับ Telegram, แบ่งหลายข้อความไม่ให้โดนตัด)
$lineRows = [];
foreach ($order_show as $st) {
    if (!empty($grouped[$st])) {
        $m = line_tracking_status($st);
        $lineRows[] = ['label' => $m['emoji'] . ' ' . $m['label'], 'value' => count($grouped[$st]), 'color' => $m['color']];
    }
}
$lineMsgs = array_merge(
    [line_report_flex('🔔 รายงานเช้า', "📅 $report_date  ⏰ $report_time น.", (string)count($all_jobs), 'รายการ', $lineRows, '#0ea5e9')],
    line_text_chunks(line_html_to_text($msg), 4800, 4)
);
$lineOut = line_alert_send($pdo, $lineMsgs);

// แสดงผลลัพธ์บนหน้าเว็บ (กรณีรัน Manual เพื่อเช็คสถานะ)
echo "<h3>✅ Morning Report Sent (Official)</h3>";
echo "<pre>Telegram: " . htmlspecialchars($res) . "</pre>";
echo "<pre>LINE: " . htmlspecialchars(json_encode($lineOut, JSON_UNESCAPED_UNICODE)) . "</pre>";
?>